const players = [
  {
    name: 'Kylian Mbappé',
    description: 'Attaquant français, champion du monde 2018.',
    position: 'Attaquant',
    era: '2017-',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Kylian_Mbapp%C3%A9_2018.jpg',
    alt: 'Kylian Mbappé avec la France en 2018',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Kylian_Mbapp%C3%A9_2018.jpg',
    sourceLabel: 'Wikimedia Commons',
    details: 'Vitesse, finition et capacité à décider les grands matchs. Profil central de l’attaque française moderne.',
    stats: { Sélections: 86, Buts: 48, Passes: 35, Trophées: 16 },
    performanceSeries: [
      { label: '2018', value: 12 },
      { label: '2021', value: 18 },
      { label: '2022', value: 21 },
      { label: '2023', value: 25 },
    ],
    honors: ['Champion du monde 2018', 'Finaliste Coupe du monde 2022', 'Meilleur buteur Coupe du monde 2022'],
  },
  {
    name: 'Antoine Griezmann',
    description: 'International français, champion du monde 2018.',
    position: 'Attaquant / milieu',
    era: '2014-',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Antoine_Griezmann_2018.jpg',
    alt: 'Antoine Griezmann en 2018',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Antoine_Griezmann_2018.jpg',
    sourceLabel: 'Wikimedia Commons',
    details: 'Joueur de liaison majeur, précieux entre les lignes par son volume, sa créativité et son sens collectif.',
    stats: { Sélections: 135, Buts: 44, Passes: 38, Trophées: 7 },
    performanceSeries: [
      { label: '2016', value: 18 },
      { label: '2018', value: 17 },
      { label: '2021', value: 13 },
      { label: '2022', value: 16 },
    ],
    honors: ['Champion du monde 2018', 'Meilleur joueur Euro 2016', 'Ligue des Nations 2021'],
  },
  {
    name: 'Thierry Henry',
    description: 'Ancien attaquant français, champion du monde 1998.',
    position: 'Attaquant',
    era: '1997-2010',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Thierry_Henry.jpg',
    alt: 'Thierry Henry',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Thierry_Henry.jpg',
    sourceLabel: 'Wikimedia Commons',
    details: 'Référence offensive d’Arsenal et des Bleus, combinant appels, vitesse et finition placée.',
    stats: { Sélections: 123, Buts: 51, Passes: 30, Trophées: 20 },
    performanceSeries: [
      { label: '2000', value: 16 },
      { label: '2003', value: 24 },
      { label: '2004', value: 30 },
      { label: '2006', value: 18 },
    ],
    honors: ['Champion du monde 1998', 'Champion d’Europe 2000', 'Invincible avec Arsenal 2004'],
  },
  {
    name: 'Zinedine Zidane',
    description: 'Ancien meneur de jeu français, Ballon d’Or 1998.',
    position: 'Milieu offensif',
    era: '1994-2006',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Zinedine_Zidane_by_Tasnim_03.jpg',
    alt: 'Zinedine Zidane en conférence de presse',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Zinedine_Zidane_by_Tasnim_03.jpg',
    sourceLabel: 'Wikimedia Commons',
    details: 'Créateur emblématique, décisif dans les moments les plus exposés de l’histoire des Bleus.',
    stats: { Sélections: 108, Buts: 31, Passes: 28, Trophées: 15 },
    performanceSeries: [
      { label: '1998', value: 20 },
      { label: '2000', value: 22 },
      { label: '2002', value: 16 },
      { label: '2006', value: 19 },
    ],
    honors: ['Ballon d’Or 1998', 'Champion du monde 1998', 'Champion d’Europe 2000'],
  },
  {
    name: 'Wendie Renard',
    description: 'Défenseure française, cadre de l’équipe de France.',
    position: 'Défenseure',
    era: '2011-',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Wendie_Renard_in_2011.JPG',
    alt: 'Wendie Renard avec la France en 2011',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Wendie_Renard_in_2011.JPG',
    sourceLabel: 'Wikimedia Commons',
    details: 'Leadership défensif, domination aérienne et longévité exceptionnelle au plus haut niveau européen.',
    stats: { Sélections: 160, Buts: 38, CleanSheets: 74, Trophées: 34 },
    performanceSeries: [
      { label: '2016', value: 18 },
      { label: '2019', value: 20 },
      { label: '2022', value: 17 },
      { label: '2024', value: 16 },
    ],
    honors: ['Multiples Ligues des champions', 'Capitaine de l’équipe de France', 'Référence historique de l’OL'],
  },
  {
    name: 'Marie-Antoinette Katoto',
    description: 'Attaquante française, référence offensive du football féminin français.',
    position: 'Attaquante',
    era: '2018-',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/20141015_-_PSG-Twente_-_Marie-Antoinette_Katoto_01.jpg',
    alt: 'Marie-Antoinette Katoto avec le PSG',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:20141015_-_PSG-Twente_-_Marie-Antoinette_Katoto_01.jpg',
    sourceLabel: 'Wikimedia Commons',
    details: 'Avant-centre puissante et efficace, habituée aux gros volumes de buts en club et en sélection.',
    stats: { Sélections: 39, Buts: 30, Passes: 9, Trophées: 5 },
    performanceSeries: [
      { label: '2019', value: 13 },
      { label: '2021', value: 22 },
      { label: '2022', value: 18 },
      { label: '2024', value: 12 },
    ],
    honors: ['Meilleure buteuse D1 Arkema', 'Cadre offensive du PSG', 'Internationale française'],
  },
  {
    name: 'Eugénie Le Sommer',
    description: 'Attaquante française, meilleure buteuse historique des Bleues.',
    position: 'Attaquante',
    era: '2009-',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/20131031_FR09_Eugenie_Le_Sommer_9156.jpg',
    alt: 'Eugénie Le Sommer',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:20131031_FR09_Eugenie_Le_Sommer_9156.jpg',
    sourceLabel: 'Wikimedia Commons',
    details: 'Grande régularité devant le but, mobilité offensive et palmarès européen dense avec Lyon.',
    stats: { Sélections: 190, Buts: 94, Passes: 45, Trophées: 30 },
    performanceSeries: [
      { label: '2012', value: 17 },
      { label: '2015', value: 19 },
      { label: '2019', value: 15 },
      { label: '2023', value: 11 },
    ],
    honors: ['Meilleure buteuse historique des Bleues', 'Multiples Ligues des champions', 'Championne de France avec Lyon'],
  },
  {
    name: 'Karim Benzema',
    description: 'Attaquant français, Ballon d’Or 2022.',
    position: 'Attaquant',
    era: '2007-2022',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Karim_Benzema_2021.jpg',
    alt: 'Karim Benzema',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Karim_Benzema_2021.jpg',
    sourceLabel: 'Wikimedia Commons',
    details: 'Avant-centre complet, très fort dans l’association, la finition et les matchs européens à haute pression.',
    stats: { Sélections: 97, Buts: 37, Passes: 20, Trophées: 31 },
    performanceSeries: [
      { label: '2012', value: 18 },
      { label: '2016', value: 20 },
      { label: '2021', value: 23 },
      { label: '2022', value: 30 },
    ],
    honors: ['Ballon d’Or 2022', 'Ligue des champions 2022', 'Ligue des Nations 2021'],
  },
  {
    name: 'Michel Platini',
    description: 'Meneur de jeu français, figure majeure des années 1980.',
    position: 'Milieu offensif',
    era: '1976-1987',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Platini_vs_canada_(cropped).jpg',
    alt: 'Michel Platini en 1984',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Platini_vs_canada_(cropped).jpg',
    sourceLabel: 'Wikimedia Commons',
    details: 'Créateur et buteur d’élite, symbole du titre européen 1984 avec une efficacité rare.',
    stats: { Sélections: 72, Buts: 41, Passes: 20, Trophées: 11 },
    performanceSeries: [
      { label: '1982', value: 16 },
      { label: '1983', value: 21 },
      { label: '1984', value: 28 },
      { label: '1985', value: 20 },
    ],
    honors: ['Triple Ballon d’Or', 'Champion d’Europe 1984', 'Meilleur buteur Euro 1984'],
  },
  {
    name: 'Désiré Doué',
    description: 'Milieu offensif français, grand espoir de la nouvelle génération.',
    position: 'Milieu offensif / ailier',
    era: '2024-',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/D%C3%A9sir%C3%A9_Dou%C3%A9_2023.jpg',
    alt: 'Désiré Doué',
    sourceUrl: 'https://commons.wikimedia.org/wiki/Special:Search/D%C3%A9sir%C3%A9_Dou%C3%A9',
    sourceLabel: 'Wikimedia Commons',
    details: 'Profil créatif, très fort dans les prises de balle orientées, les petits espaces et la percussion depuis l’axe ou le côté.',
    stats: { Sélections: 6, Buts: 1, Passes: 2, Note: 'Espoir' },
    performanceSeries: [
      { label: '2022', value: 5 },
      { label: '2023', value: 9 },
      { label: '2024', value: 14 },
      { label: '2025', value: 18 },
    ],
    honors: ['International français', 'Formé au Stade Rennais', 'Révélation offensive de sa génération'],
  },
  {
    name: 'Rayan Cherki',
    description: 'Milieu offensif français, créateur technique et imprévisible.',
    position: 'Milieu offensif',
    era: '2025-',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Rayan_Cherki_2020.jpg',
    alt: 'Rayan Cherki',
    sourceUrl: 'https://commons.wikimedia.org/wiki/Special:Search/Rayan_Cherki',
    sourceLabel: 'Wikimedia Commons',
    details: 'Joueur de déséquilibre, excellent dans la dernière passe, les dribbles courts et la création face aux blocs bas.',
    stats: { Sélections: 4, Buts: 1, Passes: 3, Note: 'Créateur' },
    performanceSeries: [
      { label: '2021', value: 7 },
      { label: '2022', value: 10 },
      { label: '2024', value: 16 },
      { label: '2025', value: 21 },
    ],
    honors: ['International français', 'Formé à l’Olympique Lyonnais', 'Finaliste olympique 2024'],
  },
  {
    name: 'Ousmane Dembélé',
    description: 'Ailier français, champion du monde 2018.',
    position: 'Ailier',
    era: '2016-',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Ousmane_Demb%C3%A9l%C3%A9_2018.jpg',
    alt: 'Ousmane Dembélé avec la France en 2018',
    sourceUrl: 'https://commons.wikimedia.org/wiki/Special:Search/Ousmane_Demb%C3%A9l%C3%A9',
    sourceLabel: 'Wikimedia Commons',
    details: 'Ailier ambidextre, capable d’accélérer très vite, d’éliminer en un contre un et de créer des décalages constants.',
    stats: { Sélections: 55, Buts: 7, Passes: 14, Trophées: 18 },
    performanceSeries: [
      { label: '2018', value: 12 },
      { label: '2021', value: 10 },
      { label: '2023', value: 17 },
      { label: '2025', value: 24 },
    ],
    honors: ['Champion du monde 2018', 'Finaliste Coupe du monde 2022', 'Champion de France avec le PSG'],
  },
  {
    name: 'Paul Pogba',
    description: 'Milieu français, champion du monde 2018.',
    position: 'Milieu',
    era: '2013-',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Paul_Pogba_2018.jpg',
    alt: 'Paul Pogba avec la France en 2018',
    sourceUrl: 'https://commons.wikimedia.org/wiki/Special:Search/Paul_Pogba',
    sourceLabel: 'Wikimedia Commons',
    details: 'Milieu complet, puissant et créatif, décisif dans la projection, la passe longue et les grands rendez-vous internationaux.',
    stats: { Sélections: 91, Buts: 11, Passes: 12, Trophées: 14 },
    performanceSeries: [
      { label: '2014', value: 15 },
      { label: '2016', value: 18 },
      { label: '2018', value: 25 },
      { label: '2021', value: 16 },
    ],
    honors: ['Champion du monde 2018', 'Ligue des Nations 2021', 'Golden Boy 2013'],
  },
  {
    name: 'Bradley Barcola',
    description: 'Ailier français, joueur de percussion et de profondeur.',
    position: 'Ailier',
    era: '2023-',
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bradley_Barcola_2024.jpg',
    alt: 'Bradley Barcola',
    sourceUrl: 'https://commons.wikimedia.org/wiki/Special:Search/Bradley_Barcola',
    sourceLabel: 'Wikimedia Commons',
    details: 'Ailier très vertical, utile pour attaquer l’espace, provoquer balle au pied et étirer les défenses adverses.',
    stats: { Sélections: 18, Buts: 3, Passes: 5, Note: 'Percussion' },
    performanceSeries: [
      { label: '2022', value: 6 },
      { label: '2023', value: 13 },
      { label: '2024', value: 20 },
      { label: '2025', value: 22 },
    ],
    honors: ['International français', 'Champion de France avec le PSG', 'Révélation offensive en Ligue 1'],
  },
];

export function activate(ctx) {
  return ctx.ui.registerAction({
    id: 'french-football-gallery',
    label: 'Afficher les footballeurs français',
    run: () => {
      ctx.ui.openGallery({
        title: 'Galerie Bleus',
        description: 'Photos de footballeurs et footballeuses français connus.',
        items: players,
      });
    },
  });
}
